// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94iue_sqDFNQaLiVNyVETBy7vzozZZHc',
    appId: '1:869948741017:web:ec6cabbb2a5729c5932f08',
    messagingSenderId: '869948741017',
    projectId: 'punjab-traffic-system',
    authDomain: 'punjab-traffic-system.firebaseapp.com',
    storageBucket: 'punjab-traffic-system.firebasestorage.app',
    measurementId: 'G-D288ETM0H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAnwut5rMCF64P9y2kSJSQK6Da__1XLlM',
    appId: '1:869948741017:android:e752f7e8adbfb9a1932f08',
    messagingSenderId: '869948741017',
    projectId: 'punjab-traffic-system',
    storageBucket: 'punjab-traffic-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr0yp3NRKNYQRRs9gvcXoHaREo9wtUFws',
    appId: '1:869948741017:ios:fd689ee44bae7037932f08',
    messagingSenderId: '869948741017',
    projectId: 'punjab-traffic-system',
    storageBucket: 'punjab-traffic-system.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr0yp3NRKNYQRRs9gvcXoHaREo9wtUFws',
    appId: '1:869948741017:ios:fd689ee44bae7037932f08',
    messagingSenderId: '869948741017',
    projectId: 'punjab-traffic-system',
    storageBucket: 'punjab-traffic-system.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA94iue_sqDFNQaLiVNyVETBy7vzozZZHc',
    appId: '1:869948741017:web:b189f52cafd10556932f08',
    messagingSenderId: '869948741017',
    projectId: 'punjab-traffic-system',
    authDomain: 'punjab-traffic-system.firebaseapp.com',
    storageBucket: 'punjab-traffic-system.firebasestorage.app',
    measurementId: 'G-1L06VXE505',
  );
}
